/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseRouteImport } from './routes/supabase'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as IndexRouteImport } from './routes/index'

const SupabaseRoute = SupabaseRouteImport.update({
  id: '/supabase',
  path: '/supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/income': typeof IncomeRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/income': typeof IncomeRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/income': typeof IncomeRoute
  '/login': typeof LoginRoute
  '/supabase': typeof SupabaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/income' | '/login' | '/supabase'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/income' | '/login' | '/supabase'
  id: '__root__' | '/' | '/income' | '/login' | '/supabase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncomeRoute: typeof IncomeRoute
  LoginRoute: typeof LoginRoute
  SupabaseRoute: typeof SupabaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase': {
      id: '/supabase'
      path: '/supabase'
      fullPath: '/supabase'
      preLoaderRoute: typeof SupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncomeRoute: IncomeRoute,
  LoginRoute: LoginRoute,
  SupabaseRoute: SupabaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
